// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Boxcon

#include "../ui.h"

void ui_HOME_screen_init(void)
{
    ui_HOME = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HOME, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_Panel1, lv_pct(110));
    lv_obj_set_height(ui_Panel1, lv_pct(105));
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, 3);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x0378CC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Panel1, lv_color_hex(0x142C59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Panel1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Panel2, 185);
    lv_obj_set_height(ui_Panel2, 50);
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, lv_pct(-10));
    lv_obj_set_align(ui_Panel2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x222121), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, 5);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Please Connect Wifi");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Status = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Status, 167);
    lv_obj_set_height(ui_Status, 181);
    lv_obj_set_x(ui_Status, -144);
    lv_obj_set_y(ui_Status, 7);
    lv_obj_set_align(ui_Status, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Status, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Status, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Status, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Status, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Status, lv_color_hex(0xEBEBEB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Status, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Status, lv_color_hex(0x575757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Status, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Status, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Status, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Status, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Status, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Status);
    lv_obj_set_width(ui_Panel6, 37);
    lv_obj_set_height(ui_Panel6, 34);
    lv_obj_set_x(ui_Panel6, 55);
    lv_obj_set_y(ui_Panel6, -65);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_stateimg = lv_img_create(ui_Panel6);
    lv_img_set_src(ui_stateimg, &ui_img_power_png);
    lv_obj_set_width(ui_stateimg, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_stateimg, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_stateimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_stateimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_stateimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_State = lv_label_create(ui_Status);
    lv_obj_set_width(ui_State, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_State, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_State, -45);
    lv_obj_set_y(ui_State, -63);
    lv_obj_set_align(ui_State, LV_ALIGN_CENTER);
    lv_label_set_text(ui_State, "State");
    lv_obj_set_style_text_color(ui_State, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_State, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_State, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Status);
    lv_obj_set_width(ui_Panel4, 138);
    lv_obj_set_height(ui_Panel4, 132);
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, 15);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BarState = lv_bar_create(ui_Panel4);
    lv_bar_set_range(ui_BarState, 0, 15);
    lv_obj_set_width(ui_BarState, 135);
    lv_obj_set_height(ui_BarState, 132);
    lv_obj_set_align(ui_BarState, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_BarState, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarState, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BarState, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BarState, 669, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_setStatus = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_setStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_setStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_setStatus, "OFF");
    lv_obj_set_style_text_color(ui_setStatus, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_setStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_setStatus, &ui_font_Kanit, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_setStatus, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_setStatus, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Time, 114);
    lv_obj_set_height(ui_Time, 83);
    lv_obj_set_x(ui_Time, 87);
    lv_obj_set_y(ui_Time, -42);
    lv_obj_set_align(ui_Time, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Time, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Time, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Time, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Time, lv_color_hex(0xEFEFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Time, lv_color_hex(0x575757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Time, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Time, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Time, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Time, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Time, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Time);
    lv_obj_set_width(ui_Panel7, 27);
    lv_obj_set_height(ui_Panel7, 28);
    lv_obj_set_x(ui_Panel7, 36);
    lv_obj_set_y(ui_Panel7, -20);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Timeicon = lv_img_create(ui_Panel7);
    lv_img_set_src(ui_Timeicon, &ui_img_time_png);
    lv_obj_set_width(ui_Timeicon, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_Timeicon, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_Timeicon, -1);
    lv_obj_set_y(ui_Timeicon, -1);
    lv_obj_set_align(ui_Timeicon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Timeicon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Timeicon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time = lv_label_create(ui_Time);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, -27);
    lv_obj_set_y(ui_time, -22);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "Time");
    lv_obj_set_style_text_color(ui_time, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setTime = lv_label_create(ui_Time);
    lv_obj_set_width(ui_setTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setTime, 1);
    lv_obj_set_y(ui_setTime, 24);
    lv_obj_set_align(ui_setTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_setTime, "00:00");
    lv_obj_set_style_text_color(ui_setTime, lv_color_hex(0x4E4E4E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_setTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_setTime, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Current = lv_obj_create(ui_Panel1);
    lv_obj_set_width(ui_Current, 114);
    lv_obj_set_height(ui_Current, 86);
    lv_obj_set_x(ui_Current, 88);
    lv_obj_set_y(ui_Current, 54);
    lv_obj_set_align(ui_Current, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Current, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Current, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Current, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Current, 210, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Current, lv_color_hex(0xEFEFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Current, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Current, lv_color_hex(0x575757), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Current, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Current, 15, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Current, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_Current, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_Current, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time1 = lv_label_create(ui_Current);
    lv_obj_set_width(ui_time1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time1, -16);
    lv_obj_set_y(ui_time1, -23);
    lv_obj_set_align(ui_time1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time1, "Current");
    lv_obj_set_style_text_color(ui_time1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_setCurrent = lv_label_create(ui_Current);
    lv_obj_set_width(ui_setCurrent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_setCurrent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_setCurrent, -21);
    lv_obj_set_y(ui_setCurrent, 8);
    lv_obj_set_align(ui_setCurrent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_setCurrent, "0");
    lv_obj_set_style_text_color(ui_setCurrent, lv_color_hex(0x4E4E4E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_setCurrent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_setCurrent, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mA = lv_label_create(ui_Current);
    lv_obj_set_width(ui_mA, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mA, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mA, 26);
    lv_obj_set_y(ui_mA, 10);
    lv_obj_set_align(ui_mA, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mA, "mA");
    lv_obj_set_style_text_color(ui_mA, lv_color_hex(0x4E4E4E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_mA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_mA, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Current);
    lv_obj_set_width(ui_Panel5, 27);
    lv_obj_set_height(ui_Panel5, 28);
    lv_obj_set_x(ui_Panel5, 36);
    lv_obj_set_y(ui_Panel5, -23);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_currenticon = lv_img_create(ui_Panel5);
    lv_img_set_src(ui_currenticon, &ui_img_currency_png);
    lv_obj_set_width(ui_currenticon, LV_SIZE_CONTENT);   /// 20
    lv_obj_set_height(ui_currenticon, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_currenticon, -1);
    lv_obj_set_y(ui_currenticon, 1);
    lv_obj_set_align(ui_currenticon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_currenticon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_currenticon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_HOME);
    lv_obj_set_width(ui_Panel3, 39);
    lv_obj_set_height(ui_Panel3, 36);
    lv_obj_set_x(ui_Panel3, -122);
    lv_obj_set_y(ui_Panel3, -96);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Homeimg = lv_img_create(ui_Panel3);
    lv_img_set_src(ui_Homeimg, &ui_img_1810231589);
    lv_obj_set_width(ui_Homeimg, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_Homeimg, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_align(ui_Homeimg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Homeimg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Homeimg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
