// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Boxcon

#include "../ui.h"

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_welcome = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_welcome, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_welcome, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_welcome, LV_ALIGN_CENTER);
    lv_label_set_text(ui_welcome, "WELCOME");
    lv_obj_set_style_text_align(ui_welcome, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_welcome, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}
