// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: Boxcon

#ifndef _BOXCON_UI_H
#define _BOXCON_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
void A1_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_welcome;
// SCREEN: ui_HOME
void ui_HOME_screen_init(void);
extern lv_obj_t * ui_HOME;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Status;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_stateimg;
extern lv_obj_t * ui_State;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_BarState;
extern lv_obj_t * ui_setStatus;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Timeicon;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_setTime;
extern lv_obj_t * ui_Current;
extern lv_obj_t * ui_time1;
extern lv_obj_t * ui_setCurrent;
extern lv_obj_t * ui_mA;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_currenticon;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Homeimg;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_power_png);    // assets\power.png
LV_IMG_DECLARE(ui_img_time_png);    // assets\time.png
LV_IMG_DECLARE(ui_img_currency_png);    // assets\currency.png
LV_IMG_DECLARE(ui_img_1810231589);    // assets\Untitled-3.png

LV_FONT_DECLARE(ui_font_Kanit);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
